example/blog/urls.py
from django.urls import path
from .views import (
    create_blog_view,
    detail_blog_view,
    edit_blog_view,
    
    
)

app_name = 'blog'
urlpatterns = [
    path('create/',create_blog_view, name='create'),
    path('<slug>/',detail_blog_view, name='detail'),
    path('<slug>/edit',edit_blog_view, name='edit'),
    
    
]

example/example/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views,urls
from django.conf import settings
from django.conf.urls.static import static

from personal.views import (
    home_screen_view,
)

from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    other_account_view,
    must_authenticate_view,
    delete,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home_screen_view, name = "home"),
    path('blog/', include('blog.urls', 'blog')),
    path('register/', registration_view, name='register'),
    path('logout/', logout_view, name='logout'),
    path('login/', login_view, name='login'),
    path('must_authenticate/', must_authenticate_view, name='must_authenticate'),
    path('account/<str:username>/', account_view, name='account'),
    path('user/<str:username>/', other_account_view, name='other_account'),
    url('avatar/', include('avatar.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^messages/', include('postman.urls','messages')),
    path('account/delete', delete, name='delete'),



    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

example/blog/models.py
from django.db import models
from django.db.models.fields.related import create_many_to_many_intermediary_model

from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.conf import settings
from django.db.models.signals import post_delete
from django.dispatch import receiver
from account.models import Account


def upload_loaction(instance, filename, **kwargs):
    file_path = 'blog/{author_id}/{title}.{filename}'.format(
        author_id = str(instance.author.id), title = str(instance.title), filename=filename
    )
    return file_path

class BlogPost(models.Model):
    title               = models.CharField(max_length=50, null= False, blank= False)
    body                = models.TextField(max_length=50000)
    image               = models.ImageField(upload_to= upload_loaction, null = False, blank= True)
    date_published      = models.DateTimeField(auto_now_add=True, verbose_name="date published")
    date_updated        = models.DateTimeField(auto_now=True, verbose_name="date updated")
    author              = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    slug                = models.SlugField(blank=True,unique = True)
    likes               = models.ManyToManyField(Account,related_name='blogpost_like')


    def number_of_likes(self):
        return self.likes.count()
    def __str__(self):
        return self.title
    @property
    def number_of_comments(self):
        return comment.objects.filter(post=self).count()

@receiver(post_delete,sender=BlogPost)
def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False)

def pre_save_blog_post_receiver(sender,instance, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.author.username+ "-" +instance.title)

pre_save.connect(pre_save_blog_post_receiver, sender= BlogPost)

class comment(models.Model):
    post                = models.ForeignKey(BlogPost,related_name="comments", on_delete=models.CASCADE)
    body                = models.TextField(max_length=250)
    date_published      = models.DateTimeField(auto_now_add=True, verbose_name="date published")
    author              = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return '%s-%s' %(self.post.title,self.author)

example/blog/forms.py
from django import forms
from .models import BlogPost,comment

class CreateBlogPostForm(forms.ModelForm):

	class Meta:
		model = BlogPost
		fields = ['title', 'body', 'image']

class NewCommentForm(forms.ModelForm):

	class Meta:
		model = comment
		fields = ['body']

class UpdateBlogPostForm(forms.ModelForm):
	class Meta:
		model = BlogPost
		fields = ['title','body','image']

	def save(self, commit=True):
		blog_post = self.instance
		blog_post.title = self.cleaned_data['title']
		blog_post.body = self.cleaned_data['body']

		if self.cleaned_data['image']:
			blog_post.image = self.cleaned_data['image']
		
		if commit:
			blog_post.save()

		return blog_post

example/blog/views.py
from xml.etree.ElementTree import Comment
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from django.http import HttpResponse
from .models import BlogPost
from .forms import CreateBlogPostForm, UpdateBlogPostForm,NewCommentForm
from account.models import Account
from django.http import HttpResponseRedirect
from django.urls import reverse


def create_blog_view(request):

	context = {}

	user = request.user
	if not user.is_authenticated:
		return redirect('must_authenticate')

	form = CreateBlogPostForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		obj = form.save(commit=False)
		author = Account.objects.filter(email =request.user.email).first()
		obj.author = author
		form = CreateBlogPostForm()
		obj.save()

	context['form'] = form

	return render(request, 'blog/create_blog.html', context)




def detail_blog_view(request, slug):
	
	context = {}
	blog_post = get_object_or_404(BlogPost, slug=slug)
	liked=False
	if request.method == 'POST':
		
		if blog_post.likes.filter(username=request.user.username).exists():
			blog_post.likes.remove(request.user)
		else:
			blog_post.likes.add(request.user)
		
		form = NewCommentForm(request.POST or None)
		if form.is_valid():
			obj = form.save(commit=False)
			author = Account.objects.filter(email =request.user.email).first()
			obj.author = author
			obj.post=blog_post
			form = NewCommentForm()
			obj.save()
		
		return HttpResponseRedirect(request.path)
		
	if blog_post.likes.filter(username=request.user.username).exists():
		liked = True

	context={'blog_post': blog_post,'number_of_likes':blog_post.number_of_likes(), 'post_is_liked':liked}

	return render(request, 'blog/detail_blog.html', context)
	
	




def edit_blog_view(request, slug):
	
	context = {}
	user = request.user
	if not user.is_authenticated:
		return redirect('must_authenticate')

	blog_post = get_object_or_404(BlogPost, slug=slug)

	if blog_post.author != user:
		return HttpResponse("You are not the author of this post.")

	if request.POST:
		form = UpdateBlogPostForm(request.POST or None, request.FILES or None, instance=blog_post)
		if form.is_valid():
			obj = form.save(commit=False)
			obj.save()
			context['success_message'] = "Updated"
			blog_post = obj
	
	form = UpdateBlogPostForm(
			initial={
					"title": blog_post.title, 
					"body": blog_post.body,
					"image": blog_post.image,
				}
			)
	context['form'] = form

	return render(request, 'blog/edit_blog.html', context)




def get_blog_queryset(query=None):
	queryset = []
	queries = query.split(" ")
	for q in queries:
		posts = BlogPost.objects.filter(
			Q(title__contains=q)|
			Q(body__icontains=q)
			).distinct()
		for post in posts:
			queryset.append(post)

	return list(set(queryset)) 

example/blog/templates/blog/create_blog.html
{% extends 'base.html' %}
{% block content %}

<style type="text/css">
  .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}
	  .container{
		  border: 5px solid white;
		  background-color: rgb(247, 130, 212);
	  }
</style>
	<div class="row">
		<div class="col-lg-7 offset-lg-1">
			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

				<!-- title -->
				<div class="form-group">
					<label for="id_title">Title</label>
					<input class="form-control" type="text" name="title" id="id_title" placeholder="Title" required autofocus>
				</div>

				<!-- Body -->
				<div class="form-group">
					<label for="id_body">Content</label>
					<textarea class="form-control" rows="10" type="text" name="body" id="my_textarea" placeholder="This blog is about..." required></textarea>
				</div>

				<!-- Image -->
				<div class="form-group"><br>
                    <label for="id_image">Image</label><br>
					<input  type="file" name="image" id="id_image" accept="image/*" required><br><br>
				</div>

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">POST</button>
			</form>	
		</div>
	</div>




{% endblock content %}

example/blog/templates/blog/detail_blog.html
{% extends 'base.html' %}
{% load avatar_tags %}

{% block content %}
<style type="text/css">
	.card{
		max-width: 80%;
	}
	.container{
		padding:0px;
	}
	a.post_links{
		color:black;
		font-weight: bold;
		text-decoration: none;
	}
	.image-circle{
		border-radius: 50%;
		width: 30px;
		height: 30px;
	}

	.borderless{
		border: none;
		background-color: rgba(250, 251, 252, 0);
	}
</style>

	<div class="row">

		<!-- Blog Post -->
		<div class="card m-auto">
			<img class="card-img-top" src={{blog_post.image.url}}>
			<div class="card-body mt-2 mb-2">
                <h2 class="card-title">{{blog_post.title}}</h2>
                <p class="card-text">{{blog_post.body|safe}}</p>
                {% if blog_post.author == request.user %}
                    <a href="{% url 'blog:edit' blog_post.slug %}" class="btn btn-primary">Update</a>
                {% endif %}
			</div>
			<div class="card-footer text-muted">
				<a class='post_links' href="{% url 'other_account' blog_post.author.username %}">{% avatar blog_post.author.email class="image-circle" id="user_avatar"%}{{blog_post.author.username}}</a><br>
			  Posted on {{blog_post.date_published}} and Updated on {{blog_post.date_updated}}<br>
			  {{blog_post.number_of_likes}}
		</div>
			<div class="card">
				
				{% if user.is_authenticated %}
					<form action="{% url 'blog:detail' blog_post.slug %}" method="POST">
						{% csrf_token %}

						{% if post_is_liked %}
							<button type="submit" name="blogpost_id" value="{{object.username}}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="red" class="bi bi-heart-fill" viewBox="0 0 16 16">
								<path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
							  </svg></button>
						{% else %}
							<button type="submit" name="blogpost_id" value="{{object.username}}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
								<path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
							  </svg></button>
						{% endif %}
					</form>
				{% else %}
						<a class="btn btn-outline-info" href="{% url 'login' %}?next={{request.path}}">Log in to like this article!</a>
				{% endif %}
				<strong class="text-secondary">{{ number_of_likes }} Like </strong>
			</div>
			<div class="card">
				<h5>Comments......</h5>
				<hr>
				<div class="row">
					<div class="col-lg-7 offset-lg-1">
						<form method="POST">{% csrf_token %}
							<!-- Body -->
							<div class="form-group">
								<strong><label for="id_body">New Comment</label></strong>
								<textarea class="form-control" rows="1" type="text" name="body" required></textarea>
							</div><br>
							<!-- Submit btn -->
							<button class="submit-button btn btn-sm btn-primary" type="submit">Add Comment</button>
						</form>	
						<hr>
					</div>
				</div>
				{%if not blog_post.comments.all%}
					No comments Yet.....
				{%else%}
					{% for comment in blog_post.comments.all%}
					<strong>{% avatar comment.author.email class="image-circle" id="user_avatar"%}{{comment.author.username}}</strong>
					<p>{{comment.body}}-<sub>{{comment.date_published}}</sub></p>
					
					<hr>
					{%endfor%}
					
				{%endif%}
						
				
			</div>
		</div>

	</div>

	

{% endblock content %}

example/blog/templates/blog/edit_blog.html
{% extends 'base.html' %}


{% block content %}
<style type="text/css">
   .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}

	.image {
	  opacity: 1;
	  transition: .5s ease;
	  backface-visibility: hidden;
	}

	.middle {
	  transition: .5s ease;
	  opacity: 0;
	  position: absolute;
	  text-align: center;
	  top: 50%;
	  left: 50%;
	  transform: translate(-50%, -50%);
	
	}
	.image-group{
		position: relative;
  		text-align: center;
  		cursor:pointer;
	}

	.image-group:hover .image {
	  opacity: 0.3;
	}

	.image-group:hover .middle {
	  opacity: 1;
	}

	.text {
	  margin: auto;
	  background-color: #4CAF50;
	  color: white;
	  font-size: 15px;
	  padding: 15px;
	}
</style>

	<div class="row">
		<div class="col-lg-7 offset-lg-1">

			{% if success_message %}
				<h3 style="color:green; text-align: center;">{{success_message}}</h3>
			{% endif %}

			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

				<!-- title -->
				<div class="form-group">
					<label for="id_title">Title</label>
					<input class="form-control" type="text" name="title" id="id_title" placeholder="Title" value="{{form.initial.title}}" required autofocus>
				</div>

				<!-- Body -->
				<div class="form-group">
					<label for="id_body">Content</label>
					<textarea class="form-control" rows="10" type="text" name="body" id="my_textarea" placeholder="This blog is about..." 
					required>{{form.initial.body}}</textarea>
				</div>

				<!-- Image -->
				<div class="form-group image-group" id="id_image_group">
					<img class="img-fluid image" src="{{form.initial.image.url}}" id="id_image_display">
					  <div class="middle">
					    <div class="text">Change image</div>
					  </div>
				</div>
				<input type="file" name="image" id="id_image_file" accept="image/*" onchange="readURL(this)">
				

				{% for field in form %}
					<p>
						{% for error in field.errors %}
							<p style="color: red">{{ error }}</p>
						{% endfor %}
					</p>
				{% endfor %}
				{% if form.non_field_errors %}
					<div style="color: red">
						<p>{{form.non_field_errors}}</p>
					</div>
				{% endif %}

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Update</button>
			</form>	
		</div>
	</div>

<script type="text/javascript">
	document.getElementById('id_image_group').onclick = function(event){
    	document.getElementById('id_image_file').click();
    };

	function readURL(input){
		var reader = new FileReader();
		reader.onload = function (e) {
            $('#id_image_display')
                .attr('src', e.target.result)
        };
		reader.readAsDataURL(input.files[0]);
	}
</script>

{% endblock content %}