example/blog/urls.py
from django.urls import path
from .views import (
    create_blog_view,
    detail_blog_view,
    edit_blog_view,
    
    
)

app_name = 'blog'
urlpatterns = [
    path('create/',create_blog_view, name='create'),
    path('<slug>/',detail_blog_view, name='detail'),
    path('<slug>/edit',edit_blog_view, name='edit'),
    
    
]

example/example/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views,urls
from django.conf import settings
from django.conf.urls.static import static

from personal.views import (
    home_screen_view,
)

from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    other_account_view,
    must_authenticate_view,
    delete,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home_screen_view, name = "home"),
    path('blog/', include('blog.urls', 'blog')),
    path('register/', registration_view, name='register'),
    path('logout/', logout_view, name='logout'),
    path('login/', login_view, name='login'),
    path('must_authenticate/', must_authenticate_view, name='must_authenticate'),
    path('account/<str:username>/', account_view, name='account'),
    path('user/<str:username>/', other_account_view, name='other_account'),
    url('avatar/', include('avatar.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^messages/', include('postman.urls','messages')),
    path('account/delete', delete, name='delete'),



    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

example/personal/models.py
from django.db import models

example/personal/views.py
from django.shortcuts import render
from operator import attrgetter

from blog.views import get_blog_queryset
from blog.models import BlogPost



def home_screen_view(request):
	
	context = {}

	query = ""
	if request.GET:
		query = request.GET['q']
		context['query'] = str(query)
	blog_posts = sorted(get_blog_queryset(query), key=attrgetter('date_updated'), reverse=True)
	context['blog_posts'] = blog_posts

	return render(request, "personal/home.html", context)

example/personal/templates/personal/home.html
{% extends 'base.html' %}
{% load static %}
{% load avatar_tags %}
{% block content %}
<style type="text/css">

	@media (max-width: 768px) { 
		.right-column{
			margin-left: 0px;
		}
	}

	@media (min-width: 768px) { 
		.right-column{
			margin-left: 0px;
		}
	}

	.blog-post-container{
		margin-bottom: 30px;
		width: 100%;
		padding:0px;
		overflow-x: hidden;
		overflow-y: scroll;
		height: 100vh;
		
	}
	::-webkit-scrollbar{
		width: 0px;
		background: transparent;
	}
	.create-post-bar{
		background-color: #f2f2f2;
		margin-bottom:20px;
	}

	.left-column{
		padding: 0px;
	}

	.right-column{
		padding:0px;
	}
	.lead{
		font-size: 17px;
	}
	::-webkit-scrollbar{
		width: 0px;
		background: transparent;
	}
</style>
	<div class="row">

		<!-- blog feed -->
		<div class="left-column col-lg-7 offset-lg-1">

			<!-- Top 'create post' bar -->
			<div class="d-lg-none mb-3">
				<div class="card m-auto d-flex flex-column p-3">
					<p class="lead"><address>Shailendra Singh, Shivam Tiwari, Shivashish Tiwari<br>Feedback At: <a href="mailto:shaelsingh000@gmail.com">shaelsingh000@gmail.com</a><br><br>
						This project is made under the supervision of Mr.Anshu Batham and Mr. Manish Jain, Dr. Virendra Swaroop Institute Of Computer Application.</address></p>
					<p class="m-auto"><a class="btn btn-primary" href="{% url 'blog:create' %}">Create post</a></p>
				</div>
			</div>
			<!-- end Top 'create post' bar -->

			<!-- Blog posts-->
			<div class="blog-post-container">
			{% if blog_posts %}
				{% for post in blog_posts %}
				
						{% include 'blog/snippets/blog_post_snippet.html' with blog_post=post %}<br>
				{% endfor %}
			{% else %}
					{% include 'blog/snippets/blog_post_snippet.html' with query=query %}<br>
			{% endif %}
			</div>
			<!-- End Blog posts-->
		</div>
		<!-- end blog feed -->


		<!-- Right 'create post' column  -->
		<div class="right-column col-lg-3 d-lg-flex d-none flex-column">

			<div class="create-post-bar d-flex flex-column p-4">
				<p class="lead"><address>Shailendra Singh, Shivam Tiwari, Shivashish Tiwari<br>Feedback At: <a href="mailto:shaelsingh000@gmail.com">shaelsingh000@gmail.com</a><br><br>
    				This project is made under the supervision of Mr.Anshu Batham and Mr. Manish Jain, Dr. Virendra Swaroop Institute Of Computer Application.</address></p>
				<p class="m-auto"><a class="btn btn-primary" href="{% url 'blog:create' %}">Create post</a></p>
			</div>
		
		</div>
		<!-- end Right 'create post' column  -->
	</div>

{% endblock content %}